[package]
name = "lhttpfs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.53"
curl = "0.4.49"
env_logger = "0.11.8"
fuser = "0.15.1"
libc = "0.2.177"
log = "0.4.28"
serde = "1.0.228"
serde_json = "1.0.145"
